In [1]:
from cv2 import imread
from pyFusion.fusion import *
from pyFusion.iqa import metrics
from pyFusion.iqa import xideasPetrovic as xp

import matplotlib.pyplot as plt

In [46]:
# Read images

#images_path = ['images/MRI-CT/ct.png', 'images/MRI-TC/mr.png']
images_path = ['images/MRI-PET/dg.png', 'images/MRI-PET/mr.png']
#images_path = ['images/MRI-SPECT/dg.png', 'images/MRI-SPECT/tc.png']
#images_path = ['images/T1-T2/t1.png', 'images/T1-T2/t2.png']

output = 'results/MRI-CT/'
images = []
for image in images_path:
    images.append(imread(image))
im0 = images[0]
im1 = images[1]

In [76]:
#fused_image = imread('/mnt/0CDA4207DA41EE10/Cristian/Immagini/Tesi/ImageFusionWavelets/MRI-CT.jpg', 0)
#fused_image = imread('/mnt/0CDA4207DA41EE10/Cristian/Immagini/Tesi/ImageFusionVisualSaliency/MRI-CT/fused.jpg', 0)
#fused_image = imread('/mnt/0CDA4207DA41EE10/Cristian/Immagini/Tesi/GFF/MRI-CT/GFF_MRI-CT.jpg')
#fused_image = imread('/mnt/0CDA4207DA41EE10/Cristian/Immagini/Tesi/GFF/MRI-PET/gff_mri_pet.jpg')
#fused_image = imread('/mnt/0CDA4207DA41EE10/Cristian/Immagini/Tesi/NSST-PAPCNN/T1-T2/t1_t2.png')
fused_image = imread('/mnt/0CDA4207DA41EE10/Cristian/Immagini/Tesi/NSST-PAPCNN/MRI-PET/mri_pet.tif')
#fused_image = imread('/mnt/0CDA4207DA41EE10/Cristian/Immagini/Tesi/NSCT-PCNN/T1-T2/t1_t2.tif')
#fused_image = imread('/mnt/0CDA4207DA41EE10/Cristian/Immagini/Tesi/NSCT-PCNN/MRI-PET/mri_pet.tif')
#fused_image = imread('/mnt/0CDA4207DA41EE10/Cristian/Immagini/Tesi/LICNN/MRI-CT/LICNN_MRI-CT.jpg')
#fused_image = imread('/mnt/0CDA4207DA41EE10/Cristian/Immagini/Tesi/LICNN/T1-T2/LICNN_t1_t2.jpg')
#fused_image = imread('results/MRI-CT/fusion_ct_mr.png',0)
#fused_image = imread('results/T1-T2/fusion_t1_t2.png')
#fused_image = imread('results/MRI-PET/fusion_dg_mr.png')

#--------------------------------LEGACY
#f = Image_fusion_tool('output')
#fused_image = f.pyramid_image_fusion(im0, im1, 'weighted')
#fused_image = f.weighted_average_fusion(im0,im1,0.7,0.3)
#fused_image = f.HSI_image_fusion(images[0],images[1]) # solo per immagini a colori
#fused_image = f.PCA_image_fusion(im0, im1)
#fused_image = f.PCA_fusion(im0, im1)

# fused_img = np.clip(fused_image, 0, 1)
# fused_image =(fused_image * 255).astype(np.uint8)
#----------------------------------

#plt.imshow(fused_image, cmap='gray')
#plt.imshow(fused_image)
# imwrite(output+'<nome>.jpg', fused_image)

In [77]:
xp.InformationPreservation(im0, im1, fused_image).calculate()

array([0.77793527, 0.8042576 , 0.77970976], dtype=float32)

In [78]:
xp.TotalFusionGain(im0, im1, fused_image).calculate()

array([0.579096 , 0.6339128, 0.6025406], dtype=float32)

In [79]:
xp.FusionLossArtifact(im0, im1, fused_image).calculate()

(array([0.16632825, 0.14952114, 0.1763834 ], dtype=float32),
 array([0.00191888, 0.00208832, 0.00201354], dtype=float32))

In [80]:
mse0 = metrics.mean_squared_error(im0, fused_image) 
mse1 = metrics.mean_squared_error(im1, fused_image) 
mean_mse = (mse0 + mse1) / 2
mean_mse  

1725.2595799763997

In [81]:
en0 = metrics.entropy_2d(im0, fused_image)
en1 = metrics.entropy_2d(im1, fused_image)
mean_entropy = (en0 + en1) / 2
mean_entropy

3.3798265431430465

In [82]:
mi0 = metrics.mutual_information_2d(im0, fused_image)
mi1 = metrics.mutual_information_2d(im1, fused_image)
mean_mi = (mi0 + mi1) / 2
mi0

0.6623833677321231

In [83]:
ssim0 = metrics.ssim(im0, fused_image, True)
ssim1 = metrics.ssim(im1, fused_image, True)
mean_ssim = (ssim0 + ssim1) / 2
mean_ssim

0.8290461454160793

In [84]:
#d0 = metrics.discrepancy(im0, fused_image)
#d1 = metrics.discrepancy(im1, fused_image)
#mean_discrepancy = (d0 + d1) / 2
#mean_discrepancy#